INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (1, N'Breakfast')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (2, N'Dinner')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (3, N'Kosher')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (4, N'Snack')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (5, N'Smoked')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (6, N'Franks')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (7, N'Chinese')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (8, N'Pre-Cooked')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (9, N'Processed Meat (Sliced)')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (10, N'Liver Sausage')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (11, N'Poultry Roll')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (12, N'Cooked Ham (Water)')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (13, N'Pizza Toppings')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (14, N'Processed Cheese')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (15, N'Smoked Ham')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (16, N'Smoked Poultry')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (17, N'6 Head Linker')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (18, N'88 & 16 Head Linker')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (19, N'12 Head Linker')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (20, N'Processed (Meat, Bulk)')
INSERT INTO [dbo].[Purpose] ([PurposeId], [Purpose]) VALUES (21, N'Co-Extrusion')
