/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [id]
      ,[BigBlend_MicroMotion_auto_NUMERICID]	  as [auto_NUMERICID]
      ,[BigBlend_MicroMotion_auto_VALUE]		  as [auto_VALUE]
      ,[BigBlend_MicroMotion_auto_TIMESTAMP]	  as [auto_TIMESTAMP]
      ,[BigBlend_MicroMotion_cell_den_NUMERICID]  as [cell_den_NUMERICID]
      ,[BigBlend_MicroMotion_cell_den_VALUE]	  as [cell_den_VALUE]
      ,[BigBlend_MicroMotion_cell_den_TIMESTAMP]  as [cell_den_TIMESTAMP]
      ,[BigBlend_MicroMotion_cell_pv_NUMERICID]	  as [cell_pv_NUMERICID]
      ,[BigBlend_MicroMotion_cell_pv_VALUE]		  as [cell_pv_VALUE]
      ,[BigBlend_MicroMotion_cell_pv_TIMESTAMP]	  as [cell_pv_TIMESTAMP]
      ,[BigBlend_MicroMotion_cell_rpm_NUMERICID]  as [cell_rpm_NUMERICID]
      ,[BigBlend_MicroMotion_cell_rpm_VALUE]	  as [cell_rpm_VALUE]
      ,[BigBlend_MicroMotion_cell_rpm_TIMESTAMP]  as [cell_rpm_TIMESTAMP]
      ,[BigBlend_MicroMotion_cell_run_NUMERICID]  as [cell_run_NUMERICID]
      ,[BigBlend_MicroMotion_cell_run_VALUE]	  as [cell_run_VALUE]
      ,[BigBlend_MicroMotion_cell_run_TIMESTAMP]  as [cell_run_TIMESTAMP]
      ,[BigBlend_MicroMotion_cell_sp_NUMERICID]	  as [cell_sp_NUMERICID]
      ,[BigBlend_MicroMotion_cell_sp_VALUE]		  as [cell_sp_VALUE]
      ,[BigBlend_MicroMotion_cell_sp_TIMESTAMP]	  as [cell_sp_TIMESTAMP]
      ,[BigBlend_MicroMotion_pulp_den_NUMERICID]  as [pulp_den_NUMERICID]
      ,[BigBlend_MicroMotion_pulp_den_VALUE]	  as [pulp_den_VALUE]
      ,[BigBlend_MicroMotion_pulp_den_TIMESTAMP]  as [pulp_den_TIMESTAMP]
      ,[BigBlend_MicroMotion_pulp_pv_NUMERICID]	  as [pulp_pv_NUMERICID]
      ,[BigBlend_MicroMotion_pulp_pv_VALUE]		  as [pulp_pv_VALUE]
      ,[BigBlend_MicroMotion_pulp_pv_TIMESTAMP]	  as [pulp_pv_TIMESTAMP]
      ,[BigBlend_MicroMotion_pulp_rpm_NUMERICID]  as [pulp_rpm_NUMERICID]
      ,[BigBlend_MicroMotion_pulp_rpm_VALUE]	  as [pulp_rpm_VALUE]
      ,[BigBlend_MicroMotion_pulp_rpm_TIMESTAMP]  as [pulp_rpm_TIMESTAMP]
      ,[BigBlend_MicroMotion_pulp_run_NUMERICID]  as [pulp_run_NUMERICID]
      ,[BigBlend_MicroMotion_pulp_run_VALUE]	  as [pulp_run_VALUE]
      ,[BigBlend_MicroMotion_pulp_run_TIMESTAMP]  as [pulp_run_TIMESTAMP]
      ,[BigBlend_MicroMotion_pulp_sp_NUMERICID]	  as [pulp_sp_NUMERICID]
      ,[BigBlend_MicroMotion_pulp_sp_VALUE]		  as [pulp_sp_VALUE]
      ,[BigBlend_MicroMotion_pulp_sp_TIMESTAMP]	  as [pulp_sp_TIMESTAMP]
  FROM [taglogs].[dbo].[BigBlend]