UPDATE [dbo].[LineTest]
    SET [TimeStamp] =        '{0}' --  <TimeStamp, datetime,>
        ,[TestGroupId] =      {1} --  <TestGroupId, int,>
        ,[LineId] =           {2} --  <LineId, int,>
        ,[SystemId] =         {3} --  <SystemId, int,>
        ,[StdSpeed] =         {4} --  <StdSpeed, int,>
        ,[Computer] =         {5} --  <Computer, int,>
        ,[BeltSpeed] =        {6} --  <BeltSpeed, int,>
        ,[DryEndSpeed] =      {7} --  <DryEndSpeed, int,>
        ,[ZoneA] =            {8} --  <ZoneA, int,>
        ,[ZoneB] =            {9} --  <ZoneB, int,>
        ,[ZoneC] =           {10} --  <ZoneC, int,>
        ,[WetDoorNumber] =   {11} --  <WetDoorNumber, int,>
        ,[CasingTemp] =      {12} --  <CasingTemp, int,>
        ,[Delm] =            {13} --  <Delm, int,>
        ,[CasingMoist] =     {14} --  <CasingMoist, int,>
        ,[CasingGlyc] =      {15} --  <CasingGlyc, int,>
        ,[Gly] =             {16} --  <Gly, int,>
        ,[CMC] =             {17} --  <CMC, int,>
        ,[Cond] =            {18} --  <Cond, int,>
        ,[pH] =              {19} --  <pH, int,>
        ,[HypoLevel] =       {20} --  <HypoLevel, int,>
        ,[Timing] =          {21} --  <Timing, int,>
		,[OilSetpoint] =	 {22} -- <OilSetpoint, int,>
		,[OilActual] =		 {23} -- <OilActual, int,>
        ,[Product] =       '{24}' --  <Product, varchar(6),>
        ,[Notes] =         '{25}' --  <Notes, varchar(50),>
    WHERE [LineTestId] = {26}