CREATE TABLE [dbo].[LineLoad Query] (
    [System]                       SMALLINT       NULL,
    [Unit]                         NVARCHAR (1)   NULL,
    [Color]                        NVARCHAR (45)  NULL,
    [Expr1003]                     NVARCHAR (255) NULL,
    [Blow @shirr (Min)]            NVARCHAR (255) NULL,
    [Expr1005]                     NVARCHAR (255) NULL,
    [Line]                         SMALLINT       NULL,
    [Status]                       NVARCHAR (8)   NULL,
    [Blow @shirr (Max)]            NVARCHAR (255) NULL,
    [Blow @shirr (Aim)]            NVARCHAR (255) NULL,
    [PCode]                        NVARCHAR (6)   NULL,
    [Plast Spec]                   NVARCHAR (5)   NULL,
    [Spec]                         NVARCHAR (6)   NULL,
    [Glut_Aim]                     FLOAT (53)     NULL,
    [ShirrMoist_Min]               FLOAT (53)     NULL,
    [ShirrMoist_Aim]               FLOAT (53)     NULL,
    [ShirrMoist_Max]               FLOAT (53)     NULL,
    [ReelMoist_Min]                FLOAT (53)     NULL,
    [ReelMoist_Aim]                FLOAT (53)     NULL,
    [ReelMoist_Max]                FLOAT (53)     NULL,
    [Gly_Min]                      FLOAT (53)     NULL,
    [Gly_Aim]                      FLOAT (53)     NULL,
    [Gly_Max]                      FLOAT (53)     NULL,
    [Oil_Min]                      FLOAT (53)     NULL,
    [Oil_Aim]                      FLOAT (53)     NULL,
    [Oil_Max]                      FLOAT (53)     NULL,
    [DryTens_shirr_Min]            FLOAT (53)     NULL,
    [DT LCL]                       REAL           NULL,
    [Wet L/F (Aim)]                FLOAT (53)     NULL,
    [Wet L/F (Min)]                FLOAT (53)     NULL,
    [Wet L/F (Max)]                FLOAT (53)     NULL,
    [LF_Min]                       REAL           NULL,
    [LF_Aim]                       FLOAT (53)     NULL,
    [LF_Max]                       REAL           NULL,
    [LF at shirr-Aim]              FLOAT (53)     NULL,
    [LF at shirr-Min]              FLOAT (53)     NULL,
    [LF at shirr-Max]              FLOAT (53)     NULL,
    [LF at shirr-LCL]              FLOAT (53)     NULL,
    [LF at shirr-UCL]              FLOAT (53)     NULL,
    [LF_LCL]                       REAL           NULL,
    [LF_UCL]                       REAL           NULL,
    [FFW_Aim]                      FLOAT (53)     NULL,
    [FFW_Min]                      FLOAT (53)     NULL,
    [FFW_Max]                      FLOAT (53)     NULL,
    [CasingWt_Aim]                 FLOAT (53)     NULL,
    [CasingWt_Min]                 FLOAT (53)     NULL,
    [CasingWt_Max]                 FLOAT (53)     NULL,
    [Sticker]                      BIT            NULL,
    [At shirr unshirr force (max)] NVARCHAR (50)  NULL,
    [At shirr unshirr force (avg)] NVARCHAR (50)  NULL,
    [Wet Tens (Min)]               NVARCHAR (255) NULL,
    [Oil Type]                     NVARCHAR (255) NULL
);

