CREATE TABLE [dbo].[ProductRecipe]
(
	[ProductRecipeId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ExtruderId] INT NOT NULL, 
    [BeltSpeed] INT NOT NULL, 
    [MeteringPumpSpeed] INT NOT NULL, 
    [WetLayFlat] INT NOT NULL, 
    [NH3FlowRateInternal] INT NOT NULL, 
    [AirInflationPressure] INT NOT NULL, 
    [NH3FlowRateExternal] INT NOT NULL, 
    [DyeId] INT NOT NULL, 
    [ExtruderSpeed] INT NOT NULL, 
    [WaterFlowRate] INT NOT NULL, 
    [BasketConductivityTarget] INT NOT NULL, 
    [PHTarget] INT NOT NULL, 
    [GlutId] INT NOT NULL, 
    [GlutFlowRate] INT NOT NULL, 
    [SolutionBatchId] INT NOT NULL, 
    [SolutionFlowRate] INT NOT NULL, 
    [GodetSpeedWash] INT NOT NULL, 
    [GodetClutchDry] INT NOT NULL, 
    [GodetSpeedPlast] INT NOT NULL, 
    [GodetSpeedDry] INT NOT NULL, 
    [FinalMoisture] INT NOT NULL, 
    [DryLayFlat] INT NOT NULL, 
    [DryerSpeed] INT NOT NULL, 
    [PolyId] INT NOT NULL, 
    [ShirrId] INT NOT NULL, 
    [ProductSpecId] INT NOT NULL, 
    CONSTRAINT [FK_ProductRecipe_Extruder] FOREIGN KEY ([ExtruderId]) REFERENCES [Extruder]([ExtruderId]), 
    CONSTRAINT [FK_ProductRecipe_Glut] FOREIGN KEY ([GlutId]) REFERENCES [Glut]([GlutId]), 
    CONSTRAINT [FK_ProductRecipe_Poly] FOREIGN KEY (PolyId) REFERENCES Poly(PolyId), 
    CONSTRAINT [FK_ProductRecipe_Shirr] FOREIGN KEY ([ShirrId]) REFERENCES [Shirr]([ShirrId]), 
    CONSTRAINT [FK_ProductRecipe_ProductSpec] FOREIGN KEY ([ProductSpecId]) REFERENCES [ProductSpec]([ProductSpecId]) 
)
