CREATE TABLE [dbo].[ProductCode] (
    [ProductCodeId]    INT            IDENTITY (1, 1) NOT NULL,
    [ProductCode]      NVARCHAR (6)   NULL,
    [ProductSpec]      NVARCHAR (6)   NULL,
    [PlastSpec]        NVARCHAR (5)   NULL,
    [WetLayflat_Aim]   FLOAT (53)     NULL,
    [WetLayflat_Min]   FLOAT (53)     NULL,
    [WetLayflat_Max]   FLOAT (53)     NULL,
    [Glut_Aim]         FLOAT (53)     NULL,
    [Glut_Max]         FLOAT (53)     NULL,
    [Glut_Min]         FLOAT (53)     NULL,
    [FFW_Aim]          FLOAT (53)     NULL,
    [FFW_Min]          FLOAT (53)     NULL,
    [FFW_Max]          FLOAT (53)     NULL,
    [CasingWt_Aim]     FLOAT (53)     NULL,
    [CasingWt_Min]     FLOAT (53)     NULL,
    [CasingWt_Max]     FLOAT (53)     NULL,
    [ShirrMoist_Aim]   FLOAT (53)     NULL,
    [ShirrMoist_Min]   FLOAT (53)     NULL,
    [ShirrMoist_Max]   FLOAT (53)     NULL,
    [ReelMoist_Aim]    FLOAT (53)     NULL,
    [ReelMoist_Min]    FLOAT (53)     NULL,
    [ReelMoist_Max]    FLOAT (53)     NULL,
    [LFShirr_Aim]      FLOAT (53)     NULL,
    [LFShirr_Min]      FLOAT (53)     NULL,
    [LFShirr_Max]      FLOAT (53)     NULL,
    [LFShirr_LCL]      FLOAT (53)     NULL,
    [LFShirr_UCL]      FLOAT (53)     NULL,
    [LF_Aim]           FLOAT (53)     NULL,
    [LF_Min]           REAL           NULL,
    [LF_Max]           REAL           NULL,
    [LF_LCL]           REAL           NULL,
    [LF_UCL]           REAL           NULL,
    [OilType]          NVARCHAR (255) NULL,
    [Oil_Aim]          FLOAT (53)     NULL,
    [Oil_Min]          FLOAT (53)     NULL,
    [Oil_Max]          FLOAT (53)     NULL,
    [Gly_Aim]          FLOAT (53)     NULL,
    [Gly_Min]          FLOAT (53)     NULL,
    [Gly_Max]          FLOAT (53)     NULL,
    [DryTensShirr_Min] FLOAT (53)     NULL,
    [Unshirr_Max]      NVARCHAR (50)  NULL,
    [Unshirr_Avg]      NVARCHAR (50)  NULL,
    [WetTens_Min]      NVARCHAR (255) NULL,
    [BlowShirr_Aim]    NVARCHAR (255) NULL,
    [BlowShirr_Min]    NVARCHAR (255) NULL,
    [BlowShirr_Max]    NVARCHAR (255) NULL,
    [DT_LCL]           REAL           NULL, 
    CONSTRAINT [PK_ProductCode] PRIMARY KEY ([ProductCodeId])
);

